#!/bin/sh

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="`dirname $0`/.."
fi

CLJSC_CP=''
for next in lib/*: src/clj: src/cljs: test/cljs; do
  CLJSC_CP=$CLJSC_CP$CLOJURESCRIPT_HOME'/'$next
done

while getopts l: f
do
    case $f in
        l) CLJSC_CP="${CLJSC_CP}:${OPTARG}";;
        \?) exit 1;;
    esac
done

java -server -cp $CLJSC_CP clojure.main
