#!/bin/sh

if [ "$CLOJURESCRIPT_HOME" = "" ]; then
  CLOJURESCRIPT_HOME="`dirname $0`/.."
fi

CLJSC_CP=''
for next in lib/*: src/clj: src/cljs: test/cljs; do
  CLJSC_CP=$CLJSC_CP$CLOJURESCRIPT_HOME'/'$next
done

while true
do
    if [ -z "$*" ]; then break; fi
    case "$1" in
        -l|-cp|--add-classpath) CLJSC_CP="${CLJSC_CP}:$2"; shift 2;;
        *) exit 1;;
    esac
done

java -server -cp $CLJSC_CP clojure.main
